### PR TITLE
Change assertThat to check the String rather than list.

### PR DESCRIPTION
**Pull request by cunningt**
Getting this error on ApplicationTest.java - need to tweak the way we use assertThat.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project spring-boot-camel-rest-sql: Compilation failure: Compilation failure:
[ERROR] /home/jenkins/spring-boot-camel-rest-sql/src/test/java/io/fabric8/quickstarts/camel/ApplicationTest.java:[74,26] cannot find symbol
[ERROR] symbol:   method element(int)
[ERROR] location: class org.assertj.core.api.AbstractListAssert<capture#1 of ?,capture#2 of ? extends java.util.List<? extends io.fabric8.quickstarts.camel.Book>,io.fabric8.quickstarts.camel.Book>
[ERROR] /home/jenkins/spring-boot-camel-rest-sql/src/test/java/io/fabric8/quickstarts/camel/ApplicationTest.java:[76,26] cannot find symbol
[ERROR] symbol:   method element(int)
[ERROR] location: class org.assertj.core.api.AbstractListAssert<capture#3 of ?,capture#4 of ? extends java.util.List<? extends io.fabric8.quickstarts.camel.Book>,io.fabric8.quickstarts.camel.Book>
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project spring-boot-camel-rest-sql: Compilation failure

### CODE REVIEW

**Comment by cunningt** [comment]
@dhirajsb Could you review please?   Getting an error on the test in this quickstart in the Fuse 7 build.

**Comment by dhirajsb** [comment]
@cunningt this looks related to https://issues.jboss.org/browse/OSFUSE-639
Is the fix not on Fuse 7 build branch?

**Comment by cunningt** [comment]
@dhirajsb Now I'm pretty confused - we're building v2.3.7 fabric8 and I see Nicola's change in the commit history for that branch, but we're still seeing the error.

**Comment by dhirajsb** [comment]
Without specifying a fabric8 version, the default version on the fuse-7.0.x.redhat branch seems to be org.assertj:assertj-core:jar:2.6.0:test, which won't work with fabric8-assert, which iirc needs 2.4.x.

**Comment by dhirajsb** [comment]
```mvn dependency:tree -Dverbose -Dincludes=org.assertj``` shows
```
[INFO] io.fabric8.quickstarts:spring-boot-camel-rest-sql:jar:1.0-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:1.5.4.RELEASE:test
[INFO] |  \- org.assertj:assertj-core:jar:2.6.0:test
[INFO] \- io.fabric8:fabric8-arquillian:jar:2.3.2:test
[INFO]    +- io.fabric8:kubernetes-assertions:jar:2.3.2:test
[INFO]    |  \- (org.assertj:assertj-core:jar:2.6.0:test - version managed from 2.4.1; omitted for duplicate)
[INFO]    \- io.fabric8:jolokia-assertions:jar:2.3.2:test
[INFO]       \- (org.assertj:assertj-core:jar:2.6.0:test - version managed from 2.4.1; omitted for duplicate)
```

Looks the fabric8 version of quickstart source doesn't have the assertj exclude, hence the source is working in PRs, but fails in product builds.

**Comment by cunningt** [comment]
@dhirajsb Here's what the quickstart is coming up with after all the alignments have been made - it looks like it's using 2.4.1.   

`
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spring-boot-camel-rest-sql ---
[INFO] io.fabric8.quickstarts:spring-boot-camel-rest-sql:jar:1.0.0.fuse-000089
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:1.5.4.RELEASE:test
[INFO] |  \- org.assertj:assertj-core:jar:2.4.1:test (version managed from 2.6.0)
[INFO] \- io.fabric8:fabric8-arquillian:jar:2.3.7.fuse-000003:test
[INFO]    +- io.fabric8:kubernetes-assertions:jar:2.3.7.fuse-000003:test
[INFO]    |  \- (org.assertj:assertj-core:jar:2.4.1:test - version managed from 2.6.0; omitted for duplicate)
[INFO]    \- io.fabric8:jolokia-assertions:jar:2.3.7.fuse-000003:test
[INFO]       \- (org.assertj:assertj-core:jar:2.4.1:test - version managed from 2.6.0; omitted for duplicate)
`
It doesn't look like the assertj exclude is there though.   

http://origin-repository.jboss.org/nexus/content/groups/ea/io/fabric8/fabric8-project-bom-camel-spring-boot/2.3.7.fuse-000004/fabric8-project-bom-camel-spring-boot-2.3.7.fuse-000004.pom

**Comment by cunningt** [comment]
@dhirajsb It doesn't look like assertj version matters - I've just tried with both 2.4.0 and 2.3.0 and I'm getting the same compilation error on the test.

**Pull request merged**
